# DH PARAMETER RECOMMENDATION

# 04
# @Date: 20180813
# @Data group count: 1
# @Base frame z: anti-parallel to gravity.
# @Polaris z: parallel to base frame y.
# @Notes: Only did one calibration round to get the result. Note that the d2 and d3 changed rather significantly.
# @Quality test result: 0.94 mm

# ---
# DH_0 TO DH_1 FRAME
theta_1: 3.141593 
alpha_1: -1.563196 
a_1: 0.005266 
d_1: 0.000000 

# DH_1 TO DH_2 FRAME
theta_2: -1.560790 
alpha_2: 1.560804 
a_2: 0.000855 
d_2: -0.002970 

# DH_2 TO DH_3 FRAME
theta_3: 0.000000 
alpha_3: 0.000000 
a_3: 0.000000 
d_3: -0.008697 

# DH_3 TO DH_4 FRAME
theta_4: 0.083931 
alpha_4: -1.557303 
a_4: 0.000533 
d_4: -0.000116 

# DH_4 TO DH_5 FRAME
# This set of result has been suspended due to huge kinematics software error introduced by this set of number. 
# We are now only taking a_5, d_5 and use the default (pi/2 or pi) for alpha and theta.
#theta_5: -1.641617 
#alpha_5: -1.483756 
#a_5: 0.008697 
#d_5: -0.000070 

theta_5: -1.570796
alpha_5: -1.570796
a_5: 0.008697 
d_5: -0.000070 



# Scale Factors
j1_scale_factor: 1.0022
j2_scale_factor: 0.978
j3_scale_factor: 0.988530 




